// <auto-generated />
using GP.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GP.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230406150341_tree")]
    partial class tree
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("GP.WebApi.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepresentanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RepresentanteId");

                    b.ToTable("Fornecedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "CNPJ DO FORNECEDOR",
                            Descricao = "Descrição Fornecedor",
                            Nome = "Matemática",
                            ProdutoId = 1,
                            RepresentanteId = 1
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "CNPJ DO FORNECEDOR",
                            Descricao = "Descrição Fornecedor",
                            Nome = "Física",
                            ProdutoId = 2,
                            RepresentanteId = 2
                        },
                        new
                        {
                            Id = 3,
                            CNPJ = "CNPJ DO FORNECEDOR",
                            Descricao = "Descrição Fornecedor",
                            Nome = "Português",
                            ProdutoId = 3,
                            RepresentanteId = 3
                        },
                        new
                        {
                            Id = 4,
                            CNPJ = "CNPJ DO FORNECEDOR",
                            Descricao = "Descrição Fornecedor",
                            Nome = "Inglês",
                            ProdutoId = 4,
                            RepresentanteId = 4
                        },
                        new
                        {
                            Id = 5,
                            CNPJ = "CNPJ DO FORNECEDOR",
                            Descricao = "Descrição Fornecedor",
                            Nome = "Programação",
                            ProdutoId = 5,
                            RepresentanteId = 5
                        });
                });

            modelBuilder.Entity("GP.WebApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataFabricacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "Kent",
                            Marca = "MARCA 01",
                            Nome = "Marta",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "ewwewewewe",
                            Marca = "MARCA 02",
                            Nome = "dsdsdsds",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "dsdsdsd",
                            Marca = "MARCA 03",
                            Nome = "dsdsdsdsd",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 4,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "cvcvvc",
                            Marca = "MARCA 04",
                            Nome = "cvvcvcvvc",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 5,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "vcxvcxvx",
                            Marca = "MARCA 05",
                            Nome = "ddsfsdfdf",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 6,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "fdsfsd",
                            Marca = "MARCA 06",
                            Nome = "bvcvcgfsg",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 7,
                            DataFabricacao = "2023-04-05T22:12:25.8187892-03:00",
                            DataValidade = "2023-04-05T22:12:25.8187892-03:00",
                            Descricao = "trtertret",
                            Marca = "MARCA 07",
                            Nome = "treteyte",
                            Situacao = "Ativo"
                        });
                });

            modelBuilder.Entity("GP.WebApi.Models.ProdutoFornecedor", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProdutoId", "FornecedorId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("ProdutosFornecedores");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            FornecedorId = 2
                        },
                        new
                        {
                            ProdutoId = 1,
                            FornecedorId = 4
                        },
                        new
                        {
                            ProdutoId = 1,
                            FornecedorId = 5
                        },
                        new
                        {
                            ProdutoId = 2,
                            FornecedorId = 1
                        },
                        new
                        {
                            ProdutoId = 2,
                            FornecedorId = 2
                        },
                        new
                        {
                            ProdutoId = 2,
                            FornecedorId = 5
                        },
                        new
                        {
                            ProdutoId = 3,
                            FornecedorId = 1
                        },
                        new
                        {
                            ProdutoId = 3,
                            FornecedorId = 2
                        },
                        new
                        {
                            ProdutoId = 3,
                            FornecedorId = 3
                        },
                        new
                        {
                            ProdutoId = 4,
                            FornecedorId = 1
                        },
                        new
                        {
                            ProdutoId = 4,
                            FornecedorId = 4
                        },
                        new
                        {
                            ProdutoId = 4,
                            FornecedorId = 5
                        },
                        new
                        {
                            ProdutoId = 5,
                            FornecedorId = 4
                        },
                        new
                        {
                            ProdutoId = 5,
                            FornecedorId = 5
                        },
                        new
                        {
                            ProdutoId = 6,
                            FornecedorId = 1
                        },
                        new
                        {
                            ProdutoId = 6,
                            FornecedorId = 2
                        },
                        new
                        {
                            ProdutoId = 6,
                            FornecedorId = 3
                        },
                        new
                        {
                            ProdutoId = 6,
                            FornecedorId = 4
                        },
                        new
                        {
                            ProdutoId = 7,
                            FornecedorId = 1
                        },
                        new
                        {
                            ProdutoId = 7,
                            FornecedorId = 2
                        },
                        new
                        {
                            ProdutoId = 7,
                            FornecedorId = 3
                        },
                        new
                        {
                            ProdutoId = 7,
                            FornecedorId = 4
                        },
                        new
                        {
                            ProdutoId = 7,
                            FornecedorId = 5
                        });
                });

            modelBuilder.Entity("GP.WebApi.Models.Representante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Representantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FornecedorId = 1,
                            Nome = "Lauro"
                        },
                        new
                        {
                            Id = 2,
                            FornecedorId = 2,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            FornecedorId = 3,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            Id = 4,
                            FornecedorId = 4,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 5,
                            FornecedorId = 5,
                            Nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("GP.WebApi.Models.Fornecedor", b =>
                {
                    b.HasOne("GP.WebApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GP.WebApi.Models.Representante", null)
                        .WithMany("Fornecedores")
                        .HasForeignKey("RepresentanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GP.WebApi.Models.ProdutoFornecedor", b =>
                {
                    b.HasOne("GP.WebApi.Models.Fornecedor", "Fornecedor")
                        .WithMany("ProdutosFornecedores")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GP.WebApi.Models.Produto", "Produto")
                        .WithMany("ProdutosFornecedores")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
